In [1]:
import pandas as pd

In [2]:
#Q4 IMDB

In [3]:
df=pd.read_excel('movies_metadata.xlsx')

In [6]:
df[['genres','original_title']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   genres          50 non-null     object
 1   original_title  50 non-null     object
dtypes: object(2)
memory usage: 932.0+ bytes

In [7]:
df.head(10)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,Unnamed: 24
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,373554033,81,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0,NaN
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,262797249,104,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0,NaN
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,0,101,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0,NaN
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,81452156,127,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0,NaN
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,76578911,106,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0,NaN
5,False,NaN,60000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",NaN,949,tt0113277,en,Heat,"Obsessive master thief, Neil McCauley leads a ...",...,187436818,170,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,A Los Angeles Crime Saga,Heat,False,7.7,1886.0,NaN
6,False,NaN,58000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",NaN,11860,tt0114319,en,Sabrina,An ugly duckling having undergone a remarkable...,...,0,127,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...",Released,You are cordially invited to the most surprisi...,Sabrina,False,6.2,141.0,NaN
7,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",NaN,45325,tt0112302,en,Tom and Huck,"A mischievous young boy, Tom Sawyer, witnesses...",...,0,97,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,The Original Bad Boys.,Tom and Huck,False,5.4,45.0,NaN
8,False,NaN,35000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",NaN,9091,tt0114576,en,Sudden Death,International action superstar Jean Claude Van...,...,64350171,106,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Terror goes into overtime.,Sudden Death,False,5.5,174.0,NaN
9,False,"{'id': 645, 'name': 'James Bond Collection', '...",58000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",http://www.mgm.com/view/movie/757/Goldeneye/,710,tt0113189,en,GoldenEye,James Bond must unmask the mysterious head of ...,...,352194034,130,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,No limits. No fears. No substitutes.,GoldenEye,False,6.6,1194.0,NaN

In [8]:
df.runtime.max() ## longest runtime

192

In [9]:
df.runtime.min() ## shortest runtime

0

In [158]:
df.sort_values(by='runtime',ascending=False)[['original_title','runtime']]

                      original_title  runtime
13                             Nixon      192
15                            Casino      178
5                               Heat      170
16             Sense and Sensibility      136
22                         Assassins      132
9                          GoldenEye      130
31                    Twelve Monkeys      129
46                             Se7en      127
3                  Waiting to Exhale      127
6                            Sabrina      127
21                           Copycat      124
25                           Othello      123
35                  Dead Man Walking      122
34                        Carrington      121
14                  Cutthroat Island      119
41                   Dead Presidents      119
42                       Restoration      117
45     How To Make An American Quilt      116
24                 Leaving Las Vegas      112
23                            Powder      111
28        La Cité des Enfants Perdus      108
44                        To Die For      106
39          Cry, the Beloved Country      106
49                The Usual Suspects      106
4        Father of the Bride Part II      106
8                       Sudden Death      106
10            The American President      106
20                        Get Shorty      105
1                            Jumanji      104
27                        Persuasion      104
40                       Richard III      104
19                       Money Train      103
2                   Grumpier Old Men      101
43                     Mortal Kombat      101
37                      It Takes Two      101
26                      Now and Then      100
30                   Dangerous Minds       99
17                        Four Rooms       98
38                          Clueless       97
7                       Tom and Huck       97
48             When Night Is Falling       96
18    Ace Ventura: When Nature Calls       90
33                              Babe       89
11       Dracula: Dead and Loving It       88
47                        Pocahontas       81
0                          Toy Story       81
12                             Balto       78
36            Across the Sea of Time       51
32  Guillaumet, les ailes du courage       50
29                               ???        0

In [15]:
df[(df.runtime>30) & (df.runtime<360)][['title','runtime']]

                             title  runtime
0                        Toy Story       81
1                          Jumanji      104
2                 Grumpier Old Men      101
3                Waiting to Exhale      127
4      Father of the Bride Part II      106
5                             Heat      170
6                          Sabrina      127
7                     Tom and Huck       97
8                     Sudden Death      106
9                        GoldenEye      130
10          The American President      106
11     Dracula: Dead and Loving It       88
12                           Balto       78
13                           Nixon      192
14                Cutthroat Island      119
15                          Casino      178
16           Sense and Sensibility      136
17                      Four Rooms       98
18  Ace Ventura: When Nature Calls       90
19                     Money Train      103
20                      Get Shorty      105
21                         Copycat      124
22                       Assassins      132
23                          Powder      111
24               Leaving Las Vegas      112
25                         Othello      123
26                    Now and Then      100
27                      Persuasion      104
28       The City of Lost Children      108
30                 Dangerous Minds       99
31                  Twelve Monkeys      129
32                Wings of Courage       50
33                            Babe       89
34                      Carrington      121
35                Dead Man Walking      122
36          Across the Sea of Time       51
37                    It Takes Two      101
38                        Clueless       97
39        Cry, the Beloved Country      106
40                     Richard III      104
41                 Dead Presidents      119
42                     Restoration      117
43                   Mortal Kombat      101
44                      To Die For      106
45   How To Make An American Quilt      116
46                           Se7en      127
47                      Pocahontas       81
48           When Night Is Falling       96
49              The Usual Suspects      106

In [16]:
#Q3

In [38]:
class Book:
    def __init__(self,title,author,publication_year,genre,num_pages):
        self.title=title
        self.author=author
        self.publication_year=publication_year
        self.numpages=numpages

    def read(self,num_pages):
        self.num_pages=num_pages
        self.num_pages=self.numpages-self.num_pages
        print(f'num of pages is {self.num_pages}')

    def change_genre(self,new_genre):
        self.new_genre=new_genre
        self.genre=new_genre
        print(f'New genre is {self.genre}')

    def set_current_year(self,current_year):
        self.current_year=current_year

    def get_age(self):
        age=self.current_year-self.publication_year
        return f'Age is {age}'

In [39]:
title=input('Enter book name: ')
author=input('Enter author name: ')
publication_year=int(input('Enter publication year: '))
genre=input("Enter genre")
numpages=int(input('Enter number of pages'))

b=Book(title,author,publication_year,genre,numpages)

Enter book name:  abcd
Enter author name:  ab
Enter publication year:  2015
Enter genre mm
Enter number of pages 250

In [40]:
num_pages=int(input('Enter number of pages: '))
b.read(num_pages)

Enter number of pages:  120

num of pages is 130

In [41]:
new_genre=input("Enter new_genre: ")
b.change_genre(new_genre)

Enter new_genre:  dd

New genre is dd

In [42]:
b.genre

'dd'

In [43]:
current_year=int(input('Enter current year: '))
b.set_current_year(current_year)
b.get_age()

Enter current year:  2024

'Age is 9'

In [44]:
#Q1

In [2]:
def anagram(s1,s2):
    cnt=0
    cnt1=0
    for i in s1:
        cnt+=1
    for i in s2:
        cnt1+=1
        
    for i in s1:
        if i not in s2:
            return False
        elif i in s2 and cnt1==cnt:
            return True
        else:
            return False

In [206]:
s1='listen'
s2='silent'
anagram(s1,s2)

True

In [198]:
s1='mayur'
s2='mayurmate'
anagram(s1,s2)

False

In [187]:
s1='mayur'
s2='ruyam'
anagram(s1,s2)

True

In [199]:
s1='hello'
s2='world'
anagram(s1,s2)

False

In [200]:
s1='mayur'
s2='mayurmate'
anagram(s1,s2)

False

In [4]:
anagram('bhakti','itkabh')

True

In [169]:
#Q2

In [209]:
l=['hello','world','hello world','goodbye']
sub='HELLO'
cnt=0
for i in l:
    if sub.lower() in i:
        cnt+=1
print(cnt)

2

In [207]:
x=50
def fun():
    global x
    print(f'global is {x}')
    x=2
    print(f'fun ele {x}')
fun()
print(f'{x}')

global is 50
fun ele 2
2

In [219]:
s=input("Enter string")
d={}
ch=input()
cnt=0
for i in s:
    if i !=' ' and ch==i:
        cnt+=1
        d.update({i:cnt})
print(d)

Enter string my name is mayur
 i

{'i': 1}

In [ ]:
s= input()
cnt=0
for i in s:

KeyError: 1

In [236]:
l=[1,2,3,4,5]
l1=l.copy()
l1

[1, 2, 3, 4, 5]

In [238]:
id(l)

3103349904576

In [239]:
id(l1)

3103349895232

In [241]:
import copy

In [243]:
l2=copy.deepcopy(l)

In [244]:
l2

[1, 2, 3, 4, 5]

In [247]:
l3=copy.copy(l2)

In [248]:
print(id(l1),id(l2))

3103349895232 3103310419200

In [249]:

d1={}
for i in d:
    d1.update({i:d.count(i)})
d1

{'a': 5, 'b': 4, 'c': 2, 'd': 2}

In [250]:
unique=[]

In [252]:
unique

['a', 'b', 'c', 'd']

In [253]:
d='aaabbabbaccdd'
max_count=0
max_char=0
unique=[]
for c in d:
    if c not in unique:
        unique.append(c)
for char in unique:
    count=0
    for c in d:
        if(char==c):
            count+=1
    if(count>max_count):
        max_count=count
        max_char=char
print(max_char)

a